### ISSUE TITLE
"Copyright/©"-Symbole crashes CSS for Debit/CC

### ISSUE THREAD

**Issue by Ekrow** [heidelpay/php-api#26]
While playing around with the examples and trying to customize the style of the debit card or credit card iframe, I edited the style.css (vendor/heidelpay/php-api/example/style.css) and was wondering why my CSS wouldn't show up.

Turns out, the CSS for the Iframe (/ngw/cssbridge?stateId=%MY_STATE_ID%) stops right before the "Copyright/©"-Symbole in the header. When I removed the symbole the CSS was indeed loaded.

Is this something common or just bad luck on my part? 

Not sure what's to fix, either not using the copyright-symbole in the css or perhaps the parser on the backend side is at fault here.

**Comment by heidelpay** [comment]
Hi @Ekrow,

first of all you can remove the header from the style.css. It is just an example.
Because of the payment card industry standard, we have to parse the css, to make sure that there are no evil elements like src etc. inside your css. 

Can you please confirm that your ccs is in UTF-8 without BOM. 

Thanks

**Comment by Ekrow** [comment]
Hi,

the CSS is indeed in UTF-8 and it works when not including the header comment, and I know I won't need comments. 
I was just wondering why it was there to begin with and why it didn't work, no worries

**Comment by heidelpay** [comment]
We will remove the copyright form css example

**Comment by heidelpay** [comment]
Fixed in #28 

Thanks @Ekrow
